# CI workflow

name: CI

on:
  push:
    branches: [ master ]

jobs:

  check:
    runs-on: ubuntu-latest
    name: Integration

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Verify with Maven
        run: mvn -B verify --file pom.xml
